#数据库
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/xmdxz?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 50
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#    password: yx668234..
  security:
    debug: false
    white: /*.html,/swagger-ui/**,/doc.html,/swagger-resources/**,/v2/**,/v3/**,/webjars/**,/swagger-ui/index.html,/login/**,/no/**

#mybatis-plus 设置
mybatis-plus:
  global-config:
    db-config:
      # 主键默认逻辑，雪花算法
      id-type: assign_id
      table-underline: true
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl #开启sql日志



#一下均为自定义设置
#swagger
swagger:
  enable: true
  name: 毕业设计
  personUrl: http://localhost:8080
  email: 1059853272@qq.com
  title: 脚手架
  description: 脚手架
  version: 1.0.0
#异步标识
async:
  core-size: 20
  max-pool-size: 100
  queue-size: 200
  keep-alive: 600
  thread-name: task-executor-
  reject-handle: CALLER
#定时任务线程池
scheduled:
  pool-size: 4

logging:
  config: classpath:config/log4j2.xml
  level:
    com.boot: warn

#百度地图请求
weather:
  url: https://api.map.baidu.com/weather/v1/
  districtId: 130582
  ak: mnnhyIuLpiDInYKbHnlKQZUGI6RLdhB8
  dataType: all
#jwt
jwt:
  secret: xmdxz_0421
  expire: 86400
  token_prefix: xmdxz
  header: Authorization
